os:
  - linux

dist: xenial

services:
  - xvfb

language: python

python:
  - 3.7
  - 3.8
  - 3.9

before_install:
  - python -m pip install --upgrade pip
  - cd TKinter
  - cd Template
install:
  - pip install -r requirements.txt

script: python3 GUI.py || python GUI.py
